### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mfindeisen** [acdh-oeaw/defc-app#1]
Hi,
I can't find any license information. Can you add a [recognized open source license](http://choosealicense.com/) if this project is available for reuse?

Thanks a million,
Matthias

**Comment by csae8092** [comment]
Hi and thanks for the question. We are currently discussing licensing policies in our department and we hope to come to a decision until the end of this week. But it will be for sure a permissive license.

**Comment by csae8092** [comment]
LICENSE added, thanks again
